version: 2
updates:
  - package-ecosystem: mix
    directory: "/"
    insecure-external-code-execution: allow
    schedule:
      interval: daily
    commit-message:
      prefix: mix
      prefix-development: mix dev
      include: scope
    open-pull-requests-limit: 5
    rebase-strategy: auto
    vendor: false
    versioning-strategy: auto
    
  - package-ecosystem: docker
    directory: "/rel/docker"
    schedule:
      interval: daily
    commit-message:
      prefix: docker
      include: scope
    open-pull-requests-limit: 5
    rebase-strategy: auto
    vendor: false
    versioning-strategy: auto
    
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: actions
      include: scope
    open-pull-requests-limit: 5
    rebase-strategy: auto
    vendor: false
    versioning-strategy: auto
